development:
  adapter: postgresql
  encoding: unicode
  database: socialstove_development
  pool: 5
  username: mihir
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: socialstove_test
  pool: 5
  username: mihir
  password:
